### ISSUE TITLE
Fails to run with latest processing

### ISSUE THREAD

**Issue by machinaut** [Interbotix/dynaManager#2]
I'm seeing a lot of compiler errors with latest processing (as of writing 3.2.3) and ControlP5.

Is there a plan for supporting processing 3?

The latest released version of the software for mac (dynamanager 1.3) works for now.

**Comment by joyyang1215** [comment]
I also see lots of compiler errors with Processing 3 and ControlP5.
I'm using Ubuntu.

**Comment by bstankie** [comment]
I'm getting a similar error. Not sure if anyone is monitoring this, but here is additional information that may help the owners/contributors. If you need additional information, I'm happy to provide. I'll document my issues and solution on my blog at [www.bstankie.com](https://www.bstankie.com).

## Solution

* Revert to [rev 1.2](https://github.com/Interbotix/dynaManager/releases/tag/1.2)

## Configuration
*  Windows 10
* Arbotix-M

## Error Information
```
ControlP5 2.0.4 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
Exception in thread "Animation Thread" java.lang.UnsatisfiedLinkError: jssc.SerialNativeInterface.getSerialPortNames()[Ljava/lang/String;
        at jssc.SerialNativeInterface.getSerialPortNames(Native Method)
        at jssc.SerialPortList.getWindowsPortNames(SerialPortList.java:309)
        at jssc.SerialPortList.getPortNames(SerialPortList.java:298)
        at jssc.SerialPortList.getPortNames(SerialPortList.java:182)
        at processing.serial.Serial.list(Unknown Source)
        at dynaManager.setup(dynaManager.java:375)
        at processing.core.PApplet.handleDraw(PApplet.java:2359)
        at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
        at processing.core.PApplet.run(PApplet.java:2254)
        at java.lang.Thread.run(Unknown Source)
```
